name: Deploy

# run only on pushing to default master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: deploy
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} # Github personal access token
          repository-name: sjyurbanlab/sjyurbanlab.github.io # The repository the action should deploy to.
          branch: master # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          clean: true # Delete files from deployment destination that no longer exist in deployment source
